name: test-action

on:
  push:
    branches: [test]
  workflow_dispatch:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        # [ubuntu-latest]
        # [windows-latest]
        # [windows-latest,ubuntu-latest]
        # [windows-latest,ubuntu-latest,macos-latest]
    name: Run UI Tests
    runs-on: ${{ matrix.os }}
    steps:
      - name: Create cluster
        id:  create-cluster
        uses: zhangjian10/nocalhost-server-cli@v0.0.3
        with:
          host: ${{ secrets.NOCALHOST_VCLUSTER_HOST_FOR_TEST }}
          email: ${{ secrets.NOCALHOST_VCLUSTER_EMAIL_FOR_TEST }}
          password: ${{ secrets.NOCALHOST_VCLUSTER_PASSWORD_FOR_TEST }}
          action: devSpace.create
      - name: Get outputs
        run: |
           echo "space_id: ${{ steps.create-cluster.outputs.space_id }}"
           echo "kubeconfig: ${{ steps.create-cluster.outputs.kubeconfig }}"
      # - name: delete cluster
      #   id:  create-cluster
      #   uses: zhangjian10/nocalhost-server-cli@v0.0.3
      #   with:
      #     host: ${{ secrets.NOCALHOST_VCLUSTER_HOST_FOR_TEST }}
      #     email: ${{ secrets.NOCALHOST_VCLUSTER_EMAIL_FOR_TEST }}
      #     password: ${{ secrets.NOCALHOST_VCLUSTER_PASSWORD_FOR_TEST }}
      #     action: devSpace.remove
      #     parameters: 1